language: cpp
os: linux
dist: focal

node_js:
  - node

branches:
  only:
  - master

git:
  depth: 1
  quiet: true
  submodules: false

services:
  - docker

before_install:
  - npm install --global @commitlint/cli@8.3.5
  - npm install --global @commitlint/travis-cli@8.3.5
  - commitlint-travis

jobs:
  include:
    - name: Build
      install:
      - docker build --tag touch_typing .
      before_script:
      - docker run -d --name touch_typing --security-opt seccomp=unconfined -v `pwd`:/touch_typing --env GTEST_OUTPUT=xml -ti touch_typing
      script:
      # Release (GCC)
      - docker exec touch_typing cmake -B/touch_typing/build -H/touch_typing -GNinja
      - docker exec touch_typing cmake --build /touch_typing/build --parallel
      - docker exec touch_typing rm -rf /touch_typing/build
      # Release (Clang)
      - docker exec --env CC=clang --env CXX=clang++ touch_typing cmake -B/touch_typing/build -H/touch_typing -GNinja
      - docker exec touch_typing cmake --build /touch_typing/build --parallel
      - docker exec touch_typing rm -rf /touch_typing/build
      # Default sanitizers
      - docker exec touch_typing cmake -B/touch_typing/build -H/touch_typing -DCMAKE_BUILD_TYPE=Debug -DENABLE_DEFAULT_SANITIZERS=ON -GNinja
      - docker exec touch_typing cmake --build /touch_typing/build --parallel
      - docker exec touch_typing cmake --build /touch_typing/build --target test
      - docker exec touch_typing rm -rf /touch_typing/build
      # Thread sanitizer
      - docker exec touch_typing cmake -B/touch_typing/build -H/touch_typing -DCMAKE_BUILD_TYPE=Debug -DENABLE_THREAD_SANITIZER=ON -GNinja
      - docker exec touch_typing cmake --build /touch_typing/build --parallel
      - docker exec touch_typing cmake --build /touch_typing/build --target test
      - docker exec touch_typing rm -rf /touch_typing/build
       # Debug (Clang)
      - docker exec --env CC=clang --env CXX=clang++ touch_typing cmake -B/touch_typing/build -H/touch_typing -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Debug -GNinja
      - docker exec touch_typing cmake --build /touch_typing/build --target clang-tidy
      - docker exec touch_typing cmake --build /touch_typing/build --target iwyu
      - docker exec touch_typing rm -rf /touch_typing/build
      # Debug (GCC)
      - docker exec touch_typing cmake -B/touch_typing/build -H/touch_typing -DCMAKE_BUILD_TYPE=Debug -GNinja
      - docker exec touch_typing cmake --build /touch_typing/build --parallel
      - docker exec touch_typing cmake --build /touch_typing/build --target test
      - docker exec touch_typing cmake --build /touch_typing/build --target kcov
      - docker exec touch_typing cmake --build /touch_typing/build --target cppcheck
      - docker exec touch_typing cmake --build /touch_typing/build --target clang-format
      - docker exec touch_typing cmake --build /touch_typing/build --target cmake-format
      - docker exec touch_typing cmake --build /touch_typing/build --target docs
      after_script:
      - ci_env=`bash <(curl -s https://codecov.io/env)`
      - docker exec $ci_env touch_typing /bin/bash -c "bash <(curl -s https://codecov.io/bash) -y /touch_typing/codecov.yml -s /touch_typing/build/kcov"
