function(set_option name description value)
    option(name description value)
    if(${name})
        message(STATUS "${name}: ON")
    else()
        message(STATUS "${name}: OFF")
    endif()
endfunction()

set_option(RUN_IWYU_ON_BUILD "Run 'iwyu' during the build" OFF)
set_option(RUN_CLANG_TIDY_ON_BUILD "Run 'clang-tidy' during the build" OFF)
set_option(ENABLE_CACHE "Enable cache" ON)
set_option(ENABLE_DEFAULT_SANITIZERS "Enable default sanitizers" OFF)
set_option(ENABLE_THREAD_SANITIZER "Enable thread sanitizer" OFF)
set_option(ENABLE_MEMORY_SANITIZER "Enable memory sanitizer" OFF)
