find_package(PkgConfig REQUIRED)
find_package(docopt REQUIRED)
find_package(spdlog REQUIRED)
find_package(fmt REQUIRED)
find_package(Microsoft.GSL REQUIRED)
pkg_check_modules(ncurses REQUIRED IMPORTED_TARGET ncurses)
