find_package(PkgConfig 0.29 REQUIRED)
find_package(docopt REQUIRED 0.6)
find_package(spdlog REQUIRED 1.5)
find_package(fmt 6.1 REQUIRED)
find_package(Microsoft.GSL 3.1 REQUIRED)
find_package(boost_serialization REQUIRED)
pkg_check_modules(ncurses REQUIRED IMPORTED_TARGET ncurses>=6.2)
